name: mapbox_gl_flutterflow_platform_interface
description: A common platform interface for the mapbox_gl plugin.
version: 1.0.1
homepage: https://github.com/Buy-Blvd/mapbox-gl-flutterflow

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.0.5

environment:
  sdk: '>=2.12.0 <4.0.0'
  flutter: ">=2.0.0"
